<?php
/**
 * Created by PhpStorm.
 * User: nick
 * Date: 2019-02-25
 * Time: 10:50
 */

namespace Touge\OssMedia;


class OssFileField extends OssField
{
    protected $view = 'oss-media::file';

    public function render()
    {
        $this->addVariables(["config"=>config("oss-media")]);
        $url_prefix = admin_url('oss-media');
        $this->script = <<<EOT
$(".btn-selector-alioss").on('click', function (event) {
    event.preventDefault();
    OssMedia.selector_alioss(this,"{$url_prefix}")
});
OssMedia.dmUploader("{$url_prefix}");
EOT;
        return parent::render(); // TODO: Change the autogenerated stub
    }
}