<?php
/**
 * Created by PhpStorm.
 * User: nick
 * Date: 2020-02-23
 * Time: 11:20
 */
namespace Touge\OssMedia;

class OssMultipleImageField extends OssField
{
    protected $view = 'oss-media::multiple-image';

    public function render(){
        $this->addVariables(["config"=>config("oss-media")]);

        $url_prefix = admin_url('oss-media');
        $this->script = <<<EOT
$(".btn-selector-multiple-image-alioss").off('click').on('click', function (event) {
    event.preventDefault();
    OssMedia.selector_alioss(this,"{$url_prefix}")
});


$("div.upload-preview").off('click', 'a.btn-destroy-multiple').on('click', 'a.btn-destroy-multiple', function(){
    event.preventDefault();
    OssMedia.destroyMultipleImage(this);
})

OssMedia.dmUploader("{$url_prefix}");

EOT;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}